python3: specify _PYTHON_PROJECT_BASE when building packages
Mimic the layout expected by sysconfig when inspecting the
_PYTHON_PROJECT_BASE environment variable by creating a couple
symlinks in staging_dir, then specify _PYTHON_PROJECT_BASE in
python3-package.mk to point to this directory.

This fixes issues, particularly in python-cryptography, where host
headers were being returned by checks in build.rs, causing 32-bit
cross-compilation to fail with an error like:

warning: cryptography-cffi@0.1.0: /builder/shared-workdir/build/sdk/staging_dir/hostpkg/include/python3.13/pyport.h:399:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."

The current version of python-cryptography does a check like:

import sysconfig; print(sysconfig.get_path('include'), end='')

Whereas latest upstream uses a more robust check using setuptools.
Pointing _PYTHON_PROJECT_BASE to a directory with the expected layout
fixes compilation for 32-bit targets in both cases.

Fixes: https://github.com/openwrt/packages/issues/28196
Fixes: https://github.com/openwrt/packages/issues/28699
Signed-off-by: Matt Merhar <mattmerhar@protonmail.com>